---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: default-app
  namespace: argocd
spec:
  timeout: 2m
  path: ./demo/artifacts/default-app
  interval: 5m
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: fsa-demo
    namespace: flux-system
  dependsOn:
  - name: fsa-installation
